### ISSUE TITLE
Construction of file names 

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#107]
I suggest we decide on one way to build file paths. Right now we use mainly 2:

1.  outname = ''.join([pathResult, os.path.sep, 'pics', os.path.sep, projectName, '_', str(i), '_compToRef'])
or
2. outname = os.path.join(pathResult, 'pics', projectName + '_' + str(i) + '_compToRef)

I'd prefer option 1, what are your opinions?

**Comment by awirb** [comment]
I think option two is easier to handle and read as there is not the os.path.sep between all the elements

**Comment by fso42** [comment]
Ah, my bad, I wanted to write option 2 ... :-)

**Comment by matthiasto** [comment]
Ok lets go for option 2, I ll change it in Aimec

**Comment by fso42** [comment]
I like the way @matthiasto did it by first building the filename  and then building the path
So I suggest (with one slight modification regarding the underscore) something like:

fileName = '_'.join( projectName, str(i), 'compToRef)
outName = os.path.join( pathResult, 'pics', fileName
