### ISSUE TITLE
Add avalanche name to plots (and release szenario name)

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#119]
Currently most plots don't have any indication which avalanche and release szenario was used. 
Either include it in plot or plotname

**Comment by awirb** [comment]
* Plots produced with: outQuickPlot, ouQuickPlotSimple, outPlotAllPeak now either include the release scenario in the plot name or the full simulation Name
* figure titles include release scenario or full simulation name, except in outQuickPlotSimple where the title corresponds to the filename

**Comment by awirb** [comment]
ToDo: Add figure title with nameOfAvalanche and subtitle that includes release area

**Comment by awirb** [comment]
fixed by PR #146  and #147
