### ISSUE TITLE
avaframe doc versioning

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#122]
It is now possible to add and see different versions of the documentation on https://docs.avaframe.org/en/latest/
The issue is that all the active AND merged branches are visible. It would be nice to be able to only see the latest (master) version, a few archived versions (for example when we will have different release versions) and the active branches, so:
latest,  V0.1, V0.2..., active_branch1, active_branch2...

A bit how it is done here https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html

**Comment by fso42** [comment]
I disabled the automatic build of pull requests. If a branch needs building, one has to activate it in the rtd - Admin

**Comment by matthiasto** [comment]
The rtd is still automatically created for every new branch...

**Comment by fso42** [comment]
Found a automation rule that was responsible for this -> should be fixed now
