### ISSUE TITLE
Make a generic runModule.rst which can be included on the module pages

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#138]

**Comment by matthiasto** [comment]
What do you mean exactly?

**Comment by fso42** [comment]
All run sections in the modules documentation are pretty much the same, with either it telling you to :+1: 

- run a certain runXXX.py script
- or call it in a certain way i.e result = modX.mainModX()

So I propose a top level page  (like the develop one) which explains what to do (with examples) and then we can either include this or link to it from each module page...

**Comment by fso42** [comment]
One general explanation of how to run certain parts of the framework (similar to workflow) and link from the `to run` (maybe to use?) sections
