### ISSUE TITLE
Establish (and save) QGIS AlphaBeta reference and compare com2AB

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#15]
Best to automate and maybe quantify (and justify) difference)

**Comment by fso42** [comment]
Add the data (the qgis results) to the benchmark folder e.g
benchmarks/Com2ABQGisReference/....

**Comment by matthiasto** [comment]
I started comparing the qgis results to the com2AB results. I found some indexes issues in com2AB which should be now fixed.
The results seem to agree pretty well when there is only one profile per shapefile but there are big differences when reading a shapefile with several profiles. Who is wrong, who is right ? that is the question...
