### ISSUE TITLE
Remove full report generation in cint file

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#161]
ah, @awirb correct me if I'm wrong, this comes from the generate export function of com1DFA itself, right? We can remove this, but that's not urgent... (i.e. version 0.2)

_Originally posted by @fso42 in https://github.com/avaframe/AvaFrame/pull/159#discussion_r508279835_

**Comment by awirb** [comment]
For the moment we should keep it as the current generateReport does not retrieve all of the parameters..

**Comment by fso42** [comment]
Closing this due to switch to python version
