### ISSUE TITLE
y'' in AlphaBeta plot -> symbol

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#179]
There's an unused symbol in the y'' equation in the main plot in the com2AB documentation

Suggestion:
either remove or explain

**Comment by matthiasto** [comment]
you mean 𝑦″=𝛾=2a ?
I think I explained it: 𝑦″=𝛾 is the curvature of this same quadratic fit.

**Comment by fso42** [comment]
Yes, but if i see it correctly, it is never used anywhere else, right?

**Comment by matthiasto** [comment]
True, If I remember it correctly it was to stay consistent with the notation in one of the cited papers
