### ISSUE TITLE
Establish a method to check convergence of the numerics

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#188]
Choose an avalanche. 
Compute the simulation varying the time step, the integration method, the mesh size or the amount of particles per cell or mass per particle .... and compare the results. 
Maybe use AIMEC to compare the results. For example the MaxPeakPressure in the cross section function of the s curvilinear coordinate. 
Except the results to converge.

**Comment by matthiasto** [comment]
This is partly delt with in the simiSol test and Dambreak test

**Comment by fso42** [comment]
Closing it: -> simiSol and Dambreak
