### ISSUE TITLE
Shift in input vs output

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#207]
Where is the origin of shift in Coordinates from input to output? 

It is inconsistent whether decimals or center/corner is used, 
and different for y and x coordinates

ncols         241
nrows         496
xllcenter     421140
yllcenter     364370
now I changed in the DEM to corner
if I get rid of the digits in the DEM this happens:
ncols         241
nrows         496
xllcenter     421140
yllcenter     364365
and it is the same if I use corner or center in this case

![dem_digits](https://user-images.githubusercontent.com/6945681/99786522-e4a58c80-2b1e-11eb-99ed-0521328f1391.png)

Is it done on entry already or on export?

Find in c-gode:
- [x] Where is simulation mesh computed

- [x] Where is conversion on output done

**Comment by fso42** [comment]
so now: DEM data
ncols         243
nrows         497
xllcenter    421139
yllcenter    364361
and here results: ncols         241
nrows         496
xllcenter     421140
yllcenter     364360
seems to be steps of 5 no?

**Comment by fso42** [comment]
On import with 1m defined grid size: (in GUI):
$ head -n 5 myDEM_HS2_Topo.asc
nCols  1001
nRows  401
xllcenter  1001.00
yllcenter -5000.50
cellsize  5
~/tmp/diffTests/testAvaHS 
$ head -n 5 my1mExport.asc 
ncols         5001
nrows         2001
xllcenter     1001
yllcenter     -5000.5
cellsize      1
Import from 5m to 1m and then export of that simulation mesh to raster

**Comment by fso42** [comment]
Cite AW: SW_Workspace.cpp -> funciton void SW_ScalarField::ExportFieldRasterAscii in line 2154 -> maybe this is where yllcenter and xllcenter are set with floor and ceil. Where does xmin come from?

line 2418 and ff: samplinggridsiize?

**Comment by awirb** [comment]
The export of the peak files happens in SW_Workspace.cpp: void SW_ScalarField::ExportFieldRasterAscii lines: 2172-2173

**Comment by fso42** [comment]
Shift comes from the interpolation needed in 2 steps:
- Input side: input DEM to simulation DEM -> unless input DEM cellsize - defaultCellSize < 1e-3
- Output side: Interpolaton from compute cells to grid coordinates (see exportRasterAutoRange)

[ShiftIssue.pdf](https://github.com/avaframe/AvaFrame/files/5726310/ShiftIssue.pdf)
