### ISSUE TITLE
Function to create folder structure

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#24]
I.e. example Input
output directories etc...

**Comment by matthiasto** [comment]
Do we really need this? Or can we just make it in the github Avaframe once and then when somebody clones it he already has the structure?

**Comment by fso42** [comment]
You mean like an empty folder structure? 
That would not work with versioning, as git only versions files: then we would have to put dummy files in there, which one has to delete one by one when one wants an empty structure...

We could use a zip file...  
However we will still have functions that create the temporary/result folders, extract results to a target directory and such, so I think a small function to create the structure is not a big effort...

**Comment by fso42** [comment]
Oh, and another reason: 
if someone install avaframe by using just 
pip install avaframe
the example is also missing...

**Comment by fso42** [comment]
See in3Utils initializeProject...
