### ISSUE TITLE
Introduce concept of result and work directory in Inputdir

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#25]
All modules should work and put their results in the same directory as input, i.e. there is:

A general work directory defined, Which looks like
avaSlide_Work/
-> INPUT -> with all the input data
|-WORK
|   |-com2AB
|-RESULTS
|   |-com2AB

etc

**Comment by fso42** [comment]
see allso #36

**Comment by awirb** [comment]
Now there is:
* Inputs (with all the input data)
* Work 
   * com1DFA
   * ana3Aimec
   * ....
* Outputs
   * com1DFA
   * ana3Aimec
   * ....

**Comment by fso42** [comment]
We should implement a generateModulePath function that generates these paths and makes them usable for outputs etc

**Comment by fso42** [comment]
duplicate of #152
