### ISSUE TITLE
Add start:stepsize:end to ini files

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#253]
For easy array generation, i.e. for parameter variations, allow for a 

Start:stepsize:end syntax in the ini files

**Comment by awirb** [comment]
Use start:end:numberofSteps instead

**Comment by fso42** [comment]
Linspace, since arange: _When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use numpy.linspace for these cases._
