### ISSUE TITLE
Remove showplot Flag from generate Topo cfgs - Use main showPlot cfg

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#298]
could be changed to use the flag in the general configuration file and remove the flag in the generateTopoCfg.ini

_Originally posted by @awirb in https://github.com/avaframe/AvaFrame/pull/295#discussion_r571873409_

Change in in3Utils/generateTopoCfg.ini and in3Utils/getReleaseAreaCfg.ini and adjust plotGeneratedDEM 

While at it, also make  plotGeneratedDEM  work with only main cfg maybe (not the DEM cfg)

**Comment by awirb** [comment]
fixed by #305
