### ISSUE TITLE
Make plotting in com2AB non-blocking

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#32]
As of now: is someone runs com2AB the plotting blocks execution until plot is closed

Either
Plot only to files
or
have a development flag to en/disable direct plotting

**Comment by matthiasto** [comment]
There is already a flag to enable/ disable the plotting or saving of the results.
I added in the fix_bug_AB a plot of the angle to visualize that every thing works properly and I will remove it before merging the branch

**Comment by fso42** [comment]
Ah nice, i didn't catch that. 
However I (generally) suggest setting those flags, i.e. the ones that block execution, to False as a default and all 'saving plot' flags to true.
