### ISSUE TITLE
Sort parameters in generateTopoCfg.ini

### ISSUE THREAD

**Issue by jtfisch** [avaframe/AvaFrame#333]
Parameters and examples should be sorted to figure out which parameter is relevant for which topo, e.g. 

C = 1000 # relevant for PF, ...

**Comment by fso42** [comment]
[](url)

**Comment by fso42** [comment]
Move demType further up and maybe list the parameters in the comment block, like
```
...
# FP [C, xEnd,  optional: channel]
...
```
