### ISSUE TITLE
Fix similarity solution and dam Break

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#334]
Fix similarity solution

With the implicit method to add the friction force, the similarity solution does not work any more...
It works using the explicit method from commit 483ea326940e250bf8481f7b35078931cff74de3

**Comment by matthiasto** [comment]
Probably same issue for the dam break and flat plane test

**Comment by awirb** [comment]
also damBreak doesn't work anymore

**Comment by awirb** [comment]
running now
