### ISSUE TITLE
Could we use the same strategy as with eg. the cfgUtils and use the modules name to get the correct folder -> would make the function more generic.

### ISSUE THREAD

**Issue by awirb** [avaframe/AvaFrame#343]
Could we use the same strategy as with eg. the cfgUtils and use the modules name to get the correct folder -> would make the function more generic. 
I am aware oft the problem with com1DFAPy also being called com1DFA, but we could put this behind a TODO/Dev flag and remove it when we move com1DFAPy...

_Originally posted by @fso42 in https://github.com/avaframe/AvaFrame/pull/342#discussion_r586725984_

**Comment by fso42** [comment]
see also #363

**Comment by fso42** [comment]
closing due to duplicate
