### ISSUE TITLE
Refactor AIMEC  

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#346]
Make it more robust  / flexible / less specific and strict

i.e. Mass balance at Tsave and not dt
Folder structure
File naming / rename

**Comment by fso42** [comment]
See also issues #345 and #343

**Comment by awirb** [comment]
* add options to choose which parameters are wanted (regarding input requirements, mb info yes/no)

**Comment by awirb** [comment]
no folder structure required anymore, dfa2Aimec fetches the paths to data files and returns a path dictionary
