### ISSUE TITLE
workflow grid in out... [com1DFAdev]

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#397]
**Description of topic** 
We now allow in com1DFAPy any cell size for the input DEM
The SPH kernel length and sph grid are independent from this DEM grid.
 
**Question**
What do we want to allow?
should every thing be completely independent?
what about the output results, should we allow to export results on another grid/cell size?

**Comment by fso42** [comment]
As discussed today:
Different mesh size and sph kernel length are allowed, but set to the _same by default_.
Output always on the computational mesh, any remeshing needs to be handle by the user during postprocessing

**Comment by matthiasto** [comment]
#406
