### ISSUE TITLE
get release area and mass exactly

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#450]
For now, we read the polygon, translate it into a raster (all cell for which the center is within the polygon are taken into account)
This raster is then used as reference to place the particles and "correct" the mass so that it matches exactly the release raster mass (not the polygon one)
Do we accept that the release raster is always bigger than the polygon or do we want to address this issue?

**Comment by matthiasto** [comment]
New method:
The release polygon is translated to a release raster (at least bigger than the polygon). Particles are initialized in this raster.
Then the particles lying outside the release polygon are removed.
The mass is not corrected anymore and the total mass of the particles might not match exactly the mass of the release polygon.
But getting the exact mass of the polygon is not easy (probably difficult for real topos analytically) and with an increasing number of particles our method should converge towards the exact mass

**Comment by fso42** [comment]
Closing, since the new method addresse the concerns sufficiently...
