### ISSUE TITLE
Split particle->particle placement

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#499]
With entrainment activated, particles may grow. At one point when they are "too big" we split them.
The new particles end up at all at the same position (position of the old too big particle).
Maybe this could be changed to place the particles randomly in the space occupied by the old particle.

The new particles are appended at the end of the array, meaning neighbor particles in space are not neighbor in memory. This could also be changed to improve computation efficiency.

**Comment by fso42** [comment]
See PR #582 for a solution to parts of this problem

**Comment by fso42** [comment]
We still need to look at the precise placement after splitting.
