### ISSUE TITLE
prepareArea - pointInPolyThreshold

### ISSUE THREAD

**Issue by awirb** [avaframe/AvaFrame#524]
when prepare area is called sometimes the parameter radius is hardcoded - as np.sqrt(2) (for example in the case of a secondary release)
- but it can be defined in the ini as thresholdPointinPoly 
- use value from ini for all cases where prepare area is called 
- or is there a reason why not

for example if the meshResolution = 1 - this will include more cells as desired

**Comment by matthiasto** [comment]
[prepareArea.pdf](https://github.com/avaframe/AvaFrame/files/7076405/prepareArea.pdf)
maybe this helps to understand better what is happening

**Comment by awirb** [comment]
so to summarize, the hardcoded radius is used to include cells that are only partly covered as well - and particles are removed from the cells whose actual location is not within the ploygon line - in the other cases where only affected cells are searched  - the tresholdPointinPoly is used to decide whether a center is inside or not.
