### ISSUE TITLE
If relTh is set via shapefile, config hash (eg. com1DFA) hash is the same

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#576]
I.e. something that's in the ini file can be changed from outside without changing the hash. This is of course also true for the other input, eg. DEM, but that is not in the ini file...

Add to documentation
we need to address this somehow -> maybe add a relTh = setFromShapefile or even add the shapefilename/hash/whatever...
Maybe hash complete input as well

**Comment by awirb** [comment]
- also relevant for filtering - if relTh read from shapefile - in the ini file coming with this sim - relTh is not what is given in the shapefile - so filtering for relTh does not work properly!

**Comment by fso42** [comment]
Document with more info:
https://hedgedoc.avaframe.org/-nx-70dzQK6T6RksSc0Qfg#
