### ISSUE TITLE
Error/Variability ranges

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#606]
- [ ] uncertainty and verification tool
- [ ] flow mode parameter variations
- [ ] input data accuracy
- [ ] convergence 
- [ ] compare idealize - @belieresfrendo 
- [ ] compare real

**Comment by jtfisch** [comment]
evels: implementation / numerics / data
variables: pfd, pfv, runout (length (pressure), angle, ...), ...
take care with the terms precision (test concerning reprodiblity) and accuracy (test against data)
