### ISSUE TITLE
Error/Inconsistency in com1DFA documentation

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#625]
(Reported by W. Fellin)

https://docs.avaframe.org/en/latest/moduleCom1DFA.html#theory
2nd equation:

- `delta_i1 tau^(b)/rho/h` implies a single direction (flow direction) effect of shear stress (x_1; delta_11 =1). With no stress across the flow direction (delta_21 = 0). Is that correct, i.e. avalanches expand laterally without friction?
 
- Inside the integral should be `sigma_33^(b)` and limits should be `A_b` (\partial A_b).

- This should also be corrected in 
https://docs.avaframe.org/en/latest/theoryCom1DFA.html#equation-momentum-balance6
( equation 14)

**Comment by matthiasto** [comment]
Regarding the first point, I think we take this into account. We say we apply friction at the bottom in the flow direction. If the avalanche expands laterally then the flow direction is not straight down but also a bit to the side. This means we also add some friction laterally too.
Regarding the second point, yes it is sigma_33^b and A_b
