### ISSUE TITLE
pytest fail when running localy

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#679]
**Describe the bug**
Pytests tends to fail when running on a local computer with local configuration files

**To Reproduce**
Just change create a local_com2ABCfg.ini and set custom parameters to true and run the pytests on your computer, it fails...

**Expected behavior**
pytests are expected to pass

Would it be possible to force pytests to ignore local ini files?

**Comment by awirb** [comment]
in which test is this the case? Should we maybe ensure when creating a pytest, what it gets as an input, so that it doesn't check for the local? except the function that tests this functionality..
