### ISSUE TITLE
make an option to vary mesh cell size and sphKernelRadius simultainiously

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#686]
Usually, the meshcellsize and sphKernelRadius are varied simultaneously. If we choose  meshcellsize=5m, we usually want sphKernelRadius = 5m. The way it is now, it is not possible to do a parameter variation on meshcellsize and sphKernelRadius since if we choose (meshcellsize, sphKernelRadius) = ([1, 5], [1,5]), we would like to have to get 2 simulations, one with (meshcellsize, sphKernelRadius) = (1, 1) the other with (meshcellsize, sphKernelRadius) = (5, 5) but we get 4 of them, the two tat we want plus  (meshcellsize, sphKernelRadius) = (1, 5)  and (meshcellsize, sphKernelRadius) = (5, 1)...

Anna's suggestion:
 hmm.. this is varied here as you want to vary it simultaneously with the meshcellsize right? maybe we could make a function of this and then call it?

_Originally posted by @awirb in https://github.com/avaframe/AvaFrame/pull/680#discussion_r826712199_

**Comment by awirb** [comment]
This is now available by setting sphKernelRadius = meshCellSize in the ini file - it is also now the default version on the master
