### ISSUE TITLE
Doc: autopay of animations in documentation

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#688]
The animations in the documentation should only start playing when the reader click on it

**Comment by matthiasto** [comment]
Did not find any easy and elegant way to make the animation play on click or hover. Should I remove it then? and replace it with a static figure?
It seems on can set the browser to block animation or let them play only once, but on firefow, it is then not possible to play it again...

**Comment by fso42** [comment]
Ok, leave it as it is, I'm closing this issue
