### ISSUE TITLE
This is almost the same as makeDomainTrans.

### ISSUE THREAD

**Issue by awirb** [avaframe/AvaFrame#696]
This is almost the same as makeDomainTrans.
Could we try to only have one function. I think it should be possible. 
If not (but I would prefer to avoid it) can you use the new sub functions (setAvaPath...) in makeDomainTrans

_Originally posted by @matthiasto in https://github.com/avaframe/AvaFrame/pull/692#discussion_r831838353_

**Comment by matthiasto** [comment]
same as #700
