### ISSUE TITLE
Installation of Avaframe in Windows - error: Microsoft Visual C++ 14.0 or greater is required. Visual Studio already installed

### ISSUE THREAD

**Issue by LucaDella8** [avaframe/AvaFrame#724]
Installing Avaframe in some machines (Windows), even if Visual Studio is already installed (Microsoft Visual Studio Community 2022 - 64 bit - Current Versione 17.2.2, Microsoft Visual C++ 2022), I get this error:

Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by fso42** [comment]
Hi Luca, 
Thanks for your bug report!

Which type of installation are you using? 

The `Standard/Operational' one (https://docs.avaframe.org/en/latest/operational.html)
or the `Development' installation (https://docs.avaframe.org/en/latest/developinstall.html) ?

At which step does that error occur then?

**Comment by LucaDella8** [comment]
Ciao Felix!

It occurs on the Developement one. I did even the Standard/Operational but this it was working fine.
I follow the steps within the manual and the error appear after this command:

python setup.py build_ext --inplace

The other steps were ok.

Thanks to you, ciao Luca


________________________________

Luca Dellarole
Civil & Environmental Engineer
Avalanche Forecaster    [https://dashboard.alpsolut.eu/resources/elements/vert80px.png]         [Website] <www.alpsolut.eu>     www.alpsolut.eu
[LinkedIn]<https://www.linkedin.com/company/alpsolut/>  LinkedIn<https://www.linkedin.com/company/alpsolut/>
***@***.***>   ***@***.******@***.***>     [Facebook] <https://www.facebook.com/alpsolut.eu>       Facebook<https://www.facebook.com/alpsolut.eu>
[Phone]<tel:+393398422668>      +39 339 842 26 68<tel:+393398422668>    [Address] <https://goo.gl/maps/CKNK2daDLuEfQnud6>       Via Saroch 1098/A, 23041 - Livigno (SO), Italy<https://goo.gl/maps/CKNK2daDLuEfQnud6>
[https://dashboard.alpsolut.eu/resources/elements/hor640px.png]
[Alpsolut s.r.l.]<www.alpsolut.eu>      [https://dashboard.alpsolut.eu/resources/elements/vert80px.png]
In partnership with<https://www.livigno.eu/>
[Livigno]<https://www.livigno.eu/>
Le informazioni contenute nella presente comunicazione ed i relativi allegati possono essere riservate e sono, comunque, destinate esclusivamente alle persone o alla società sopraindicate e non sono da considerarsi comunicazioni personali, quindi eventuali risposte potranno essere conosciute da persone appartenenti all'azienda. La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi dell'art.616 c.p., che ai sensi del GDPR (General Data Protection Regulation) - Reg.UE n.679/16. Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di informarci immediatamente inviando un messaggio all'indirizzo ***@***.******@***.***>

________________________________
Da: Felix Oesterle ***@***.***>
Inviato: lunedì 30 maggio 2022 08:46
A: avaframe/AvaFrame ***@***.***>
Cc: Luca Dellarole ***@***.***>; Author ***@***.***>
Oggetto: Re: [avaframe/AvaFrame] Installation of Avaframe in Windows - error: Microsoft Visual C++ 14.0 or greater is required. Visual Studio already installed (Issue #724)


Hi Luca,
Thanks for your bug report!

Which type of installation are you using?

The Standard/Operational' one (https://docs.avaframe.org/en/latest/operational.html) or the Development' installation (https://docs.avaframe.org/en/latest/developinstall.html) ?

At which step does that error occur then?

**Comment by fso42** [comment]
Thanks. I'll fire up a new Windows instance and see whether I can reproduce the error. 
My first impression is that it has to do with the local python / c++-compiler environment. We don't put any requirements on this, except it has to be python > 3.6. Any c++ compiler requirements come from the python-system itself...

**Comment by LucaDella8** [comment]
Ok thanks.

In case I should do something, let me know.

Ciao Luca

________________________________

Luca Dellarole
Civil & Environmental Engineer
Avalanche Forecaster    [https://dashboard.alpsolut.eu/resources/elements/vert80px.png]         [Website] <www.alpsolut.eu>     www.alpsolut.eu
[LinkedIn]<https://www.linkedin.com/company/alpsolut/>  LinkedIn<https://www.linkedin.com/company/alpsolut/>
***@***.***>   ***@***.******@***.***>     [Facebook] <https://www.facebook.com/alpsolut.eu>       Facebook<https://www.facebook.com/alpsolut.eu>
[Phone]<tel:+393398422668>      +39 339 842 26 68<tel:+393398422668>    [Address] <https://goo.gl/maps/CKNK2daDLuEfQnud6>       Via Saroch 1098/A, 23041 - Livigno (SO), Italy<https://goo.gl/maps/CKNK2daDLuEfQnud6>
[https://dashboard.alpsolut.eu/resources/elements/hor640px.png]
[Alpsolut s.r.l.]<www.alpsolut.eu>      [https://dashboard.alpsolut.eu/resources/elements/vert80px.png]
In partnership with<https://www.livigno.eu/>
[Livigno]<https://www.livigno.eu/>
Le informazioni contenute nella presente comunicazione ed i relativi allegati possono essere riservate e sono, comunque, destinate esclusivamente alle persone o alla società sopraindicate e non sono da considerarsi comunicazioni personali, quindi eventuali risposte potranno essere conosciute da persone appartenenti all'azienda. La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi dell'art.616 c.p., che ai sensi del GDPR (General Data Protection Regulation) - Reg.UE n.679/16. Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di informarci immediatamente inviando un messaggio all'indirizzo ***@***.******@***.***>
________________________________
Da: Felix Oesterle ***@***.***>
Inviato: lunedì 30 maggio 2022 11:08
A: avaframe/AvaFrame ***@***.***>
Cc: Luca Dellarole ***@***.***>; Author ***@***.***>
Oggetto: Re: [avaframe/AvaFrame] Installation of Avaframe in Windows - error: Microsoft Visual C++ 14.0 or greater is required. Visual Studio already installed (Issue #724)


Thanks. I'll fire up a new Windows instance and see whether I can reproduce the error.
My first impression is that it has to do with the local python / c++-compiler environment. We don't put any requirements on this, except it has to be python > 3.6. Any c++ compiler requirements come from the python-system itself...

**Comment by fso42** [comment]
Hi Luca, 
I tested it on two different machines, but I could not reproduce the error. 
Do you have more information on :
- the version of Windows
- the type of installation of your python (anaconda, direct,...)
that you used?

In my case, both machines were freshly set up...

**Comment by LucaDella8** [comment]
Before the installation I did a kind of freshly set up, uninstillling QGIS / Python / Miniconda ....
And then starting from the beginning as explain within the Avaframe manual.

These are the information:

- windows 10
- miniconda3
- python installed from Miniconda
- visual studio version 2022

Next week I will try again with a fresh installation again.

Just to know, in which step of the installation you install Visual studio and which version?

I will let you know.



________________________________

Luca Dellarole
Civil & Environmental Engineer
Avalanche Forecaster    [https://dashboard.alpsolut.eu/resources/elements/vert80px.png]         [Website] <www.alpsolut.eu>     www.alpsolut.eu
[LinkedIn]<https://www.linkedin.com/company/alpsolut/>  LinkedIn<https://www.linkedin.com/company/alpsolut/>
***@***.***>   ***@***.******@***.***>     [Facebook] <https://www.facebook.com/alpsolut.eu>       Facebook<https://www.facebook.com/alpsolut.eu>
[Phone]<tel:+393398422668>      +39 339 842 26 68<tel:+393398422668>    [Address] <https://goo.gl/maps/CKNK2daDLuEfQnud6>       Via Saroch 1098/A, 23041 - Livigno (SO), Italy<https://goo.gl/maps/CKNK2daDLuEfQnud6>
[https://dashboard.alpsolut.eu/resources/elements/hor640px.png]
[Alpsolut s.r.l.]<www.alpsolut.eu>      [https://dashboard.alpsolut.eu/resources/elements/vert80px.png]
In partnership with<https://www.livigno.eu/>
[Livigno]<https://www.livigno.eu/>
Le informazioni contenute nella presente comunicazione ed i relativi allegati possono essere riservate e sono, comunque, destinate esclusivamente alle persone o alla società sopraindicate e non sono da considerarsi comunicazioni personali, quindi eventuali risposte potranno essere conosciute da persone appartenenti all'azienda. La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi dell'art.616 c.p., che ai sensi del GDPR (General Data Protection Regulation) - Reg.UE n.679/16. Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di informarci immediatamente inviando un messaggio all'indirizzo ***@***.******@***.***>
________________________________
Da: Felix Oesterle ***@***.***>
Inviato: martedì 7 giugno 2022 12:59
A: avaframe/AvaFrame ***@***.***>
Cc: Luca Dellarole ***@***.***>; Author ***@***.***>
Oggetto: Re: [avaframe/AvaFrame] Installation of Avaframe in Windows - error: Microsoft Visual C++ 14.0 or greater is required. Visual Studio already installed (Issue #724)


Hi Luca,
I tested it on two different machines, but I could not reproduce the error.
Do you have more information on :

  *   the version of Windows
  *   the type of installation of your python (anaconda, direct,...)
that you used?

In my case, both machines were freshly set up...

**Comment by LucaDella8** [comment]
Hello Felix, I tried with a kind of fresh installation (uninstall Python, QGIS e Miniconda, VisualStudio), then try again but I still have the same problem.
The problem is that a normal user has already some software as QGIS, Python, R installed and it is impossible to have a freshly set up...
So it should work even in a pc not freshly set up.

**Comment by fso42** [comment]
Hi Luca, 
I could not reproduce this error. I'm pretty sure it has to do with your windows/python/Visual studio installation. I did not follow any particular order of installation...

Maybe for you, the Visual Build Tools are missing? 
See https://stackoverflow.com/a/55370133 or https://exerror.com/error-microsoft-visual-c-14-0-is-required-get-it-with-microsoft-visual-c-build-tools/ or https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst

In my case, I have the following in my Windows:
![2022-07-04_10-08_1](https://user-images.githubusercontent.com/6945681/177112152-0fed6397-6c15-4dc6-bd59-80c6b18a6026.png)

Let me know if this solves it for you so I can include it in the troubleshooting documentation. 

Kind regards, 
Felix

**Comment by LucaDella8** [comment]
Ciao Felix,

after resetting the pc to a fresh mode I can manage to install the development mode of Avaframe.

Here what I did:
1- resetting windows with the recovery options of windows
2- install visual studio (2022 version Desktop developement with C++ and Linux too)
3- install Miniconda
4- From Miniconda terminal installing git
5- following the installation steps: https://docs.avaframe.org/en/latest/developinstall.html#development-installation, before the git command I had to install git within the Avaframe_env
6- before running the setup.py, i did the command: conda install -c conda-forge m2w64-gcc
7- following with the rest of installation and it works!

Thanks Luca

**Comment by fso42** [comment]
Thanks, Luca, for your feedback!
