### ISSUE TITLE
Impossible loading plugin Avaframe connector on mac

### ISSUE THREAD

**Issue by LucaDella8** [avaframe/AvaFrame#733]
Hello,
I'm trying to add the AvaFrameConnector plugin to Qgis (Standard / Operational installation).
But I got the error:
Impossible to load the plugin 'avaframeConnector' due to an error calling the method classFactory()
ModuleNotFoundError: No module named 'avaframe'

1) QGIS already installed in my pc
2) Open the terminal
3) python3 -m pip install --user avaframe
4) python3 -m pip install --user --upgrade numpy pandas
5) open QGIS and try to add the plugin within the Manage Install Plugins
6) Got the error

These are the error print screen:

<img width="1076" alt="Schermata 2022-07-01 alle 11 17 55" src="https://user-images.githubusercontent.com/102517410/176893506-3022f7d5-1d7d-43c4-9547-54605f45b4cf.png">

<img width="1074" alt="Schermata 2022-07-01 alle 11 18 05" src="https://user-images.githubusercontent.com/102517410/176893549-0a48323c-852a-4c02-8ad2-71da072c5f1c.png">

OS: macOS Monterey, version 12.4

Thanks, Luca

**Comment by fso42** [comment]
Hi Luca, 
Thanks for your report!

It seems QGis uses another python installation than the system one on Mac OS, or it does not honour the user-installed packages. I don't have a Mac on hand to test this. 
I see the following possible solutions:

- You could try to install avaframe without the '--user' option. 

- I previously managed to install avaframe on an older macOS version; see #581. This works by staying in the same conda python environment. Unfortunately, the version of QGis supplied via conda forge is still 3.18, which is not very satisfactory...

- Try to install avaframe from within QGis (via the console); see here: https://gis.stackexchange.com/questions/418274/installing-python-module-using-pip-via-python-console-in-qgis-3-22

Maybe one of these helps...

**Comment by fso42** [comment]
Hi Luca, 
I have some feedback from another macOS user (thanks, Rudi!); he has it running on macOS. 

He has the following feedback on your problem:

- To install avaframe with the QGis python, he uses:
```
cd /Applications/QGIS.app/Contents/MacOS/bin/
./python3 -m pip install avaframe
./python3 -m pip install --user --upgrade numpy pandas.
```
The info about AvaFrame not being found pops up from time to time without any discernable pattern. 
He then calls  `python3 -m pip show avaframe` and `python3 -m pip show numpy`, and it works again. 

 To avoid having to do this all the time, he automated it via Automator or shell script:

```
python3 -m pip show numpy
python3 -m pip show avaframe
/Applications/QGIS-LTR.app/Contents/MacOS/QGIS.
```

However, be aware: inside QGis, he has to run it in batch mode: 
![image](https://user-images.githubusercontent.com/6945681/177298132-a1c0d8fa-95f7-4411-a50b-bab05522ae66.png)

**Comment by LucaDella8** [comment]
Ciao Felix, yesterday somehow I was trying something similar to that solution.

So working within the QGIS python, but I was getting the same error that I have now, making the steps you list.

Installing avaframe, numpy and pandas within:

/Applications/QGIS.app/Contents/MacOS/bin/


Using:

$ ./python3 -m pip show avaframe

I got the right location, for both avaframe and numpy:

Location: /Applications/QGIS-LTR.app/Contents/Resources/python/site-packages

Than I open QGIS from the command line:

/Applications/QGIS-LTR.app/Contents/MacOS/QGIS

And finally I try to add the the Plugin but I have this error:

[cid:F0F26BA3-5ED0-4352-9E49-3919187675BC]

________________________________

Luca Dellarole
Civil & Environmental Engineer
Avalanche Forecaster    [https://dashboard.alpsolut.eu/resources/elements/vert80px.png]         [Website] <www.alpsolut.eu>     www.alpsolut.eu
[LinkedIn]<https://www.linkedin.com/company/alpsolut/>  LinkedIn<https://www.linkedin.com/company/alpsolut/>
***@***.***>   ***@***.******@***.***>     [Facebook] <https://www.facebook.com/alpsolut.eu>       Facebook<https://www.facebook.com/alpsolut.eu>
[Phone]<tel:+393398422668>      +39 339 842 26 68<tel:+393398422668>    [Address] <https://goo.gl/maps/CKNK2daDLuEfQnud6>       Via Saroch 1098/A, 23041 - Livigno (SO), Italy<https://goo.gl/maps/CKNK2daDLuEfQnud6>
[https://dashboard.alpsolut.eu/resources/elements/hor640px.png]
[Alpsolut s.r.l.]<www.alpsolut.eu>      [https://dashboard.alpsolut.eu/resources/elements/vert80px.png]
In partnership with<https://www.livigno.eu/>
[Livigno]<https://www.livigno.eu/>
Le informazioni contenute nella presente comunicazione ed i relativi allegati possono essere riservate e sono, comunque, destinate esclusivamente alle persone o alla società sopraindicate e non sono da considerarsi comunicazioni personali, quindi eventuali risposte potranno essere conosciute da persone appartenenti all'azienda. La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è proibita, sia ai sensi dell'art.616 c.p., che ai sensi del GDPR (General Data Protection Regulation) - Reg.UE n.679/16. Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo e di informarci immediatamente inviando un messaggio all'indirizzo ***@***.******@***.***>




Il giorno 5 lug 2022, alle ore 11:34, Felix Oesterle ***@***.******@***.***>> ha scritto:



Hi Luca,
I have some feedback from another macOS user (thanks, Rudi!); he has it running on macOS.

He has the following feedback on your problem:

  *   To install avaframe with the QGis python, he uses:

cd /Applications/QGIS.app/Contents/MacOS/bin/
./python3 -m pip install avaframe
./python3 -m pip install --user --upgrade numpy pandas.


The info about AvaFrame not being found pops up from time to time without any discernable pattern.
He then calls python3 -m pip show avaframe and python3 -m pip show numpy, and it works again.

To avoid having to do this all the time, he automated it via Automator or shell script:

python3 -m pip show numpy
python3 -m pip show avaframe
/Applications/QGIS-LTR.app/Contents/MacOS/QGIS.


However, be aware: inside QGis, he has to run it in batch mode:
[image]<https://user-images.githubusercontent.com/6945681/177298132-a1c0d8fa-95f7-4411-a50b-bab05522ae66.png>

**Comment by fso42** [comment]
Hi Luca, I can't see your error, there seems to be an image missing?

**Comment by LucaDella8** [comment]
I update the link with the screenshot

**Comment by fso42** [comment]
Since you are on the development installation, you need to do the 
`python setup.py build_ext --inplace`
step. 
At least I think that's what's missing here...

**Comment by LucaDella8** [comment]
Why you say I'm on the development installation? Here I'm trying to install the Plugin in QGIS to use the Standard / Operational installation.

**Comment by fso42** [comment]
Uh sorry, I got that wrong! 
I'm currently releasing version 1.2, maybe you can try to update once I updated the pip installation files...
