### ISSUE TITLE
Nuisance with matplotlib backend 'agg'

### ISSUE THREAD

**Issue by snowtechblog** [avaframe/AvaFrame#745]
PS: I create a new issue, since I think I placed my initial comment in an already merge thus solved issue and it does not show up in the issue list.

I came across the nuisance with the matplotlib backend 'agg' because some functions import the outDebugPlots.py even though no debugPlots are requested.

Perhaps one could wrap their import statement into a if-clause
```
if debugPlot:
    import avaframe.out3Plot.outDebugPlots as debPlot
```
 in `com1DFA.py`, line 47, and in `particleInitialisation.py`, line 23.

_Originally posted by @snowtechblog in https://github.com/avaframe/AvaFrame/issues/511#issuecomment-1196472685_

**Comment by fso42** [comment]
related to #573
