### ISSUE TITLE
Add a simple dam model to the DFA simulations

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#747]
**Description of topic** 
Add a simple model to take dam interaction into account (based on what is implemented in SamosAT)

**Related AvaFrame functions**
Will add a dam module with preprocessing functions and the dam interaction functions

Describe the model properly in the documentation

**Comment by matthiasto** [comment]
[Scan – 2022-08-01 08_21_50.pdf](https://github.com/avaframe/AvaFrame/files/9232417/Scan.2022-08-01.08_21_50.pdf)
[Scan – 2022-08-01 08_22_46.pdf](https://github.com/avaframe/AvaFrame/files/9232419/Scan.2022-08-01.08_22_46.pdf)

**Comment by matthiasto** [comment]
We have a couple of issues with what is implemented in the samosAT version:
 - The tangent to the dam foot line does not correspond to the line you se in qgis... This leads to particles still crossing the dam line even if they shouldn't
 - what happens if the flow thickness exceeds the dam height?
 - Because of the way the particles are reflected and reprojected, having a small restitution coefficient (meaning not elastic bouncing) sometimes leads to particles going further

**Comment by fso42** [comment]
closed with #756
