### ISSUE TITLE
Override Section issue

### ISSUE THREAD

**Issue by matthiasto** [avaframe/AvaFrame#758]
**Describe the bug**
 when using the Override section, for example [com1DFA_override] in the energyLinteTestCfg.ini, new parameters in Override Section in the local version are ignored... So lets say in the local_energyLinteTestCfg.ini in the [com1DFA_override] section, I want to change the sphKernelRadius, I can't because this is not in the energyLinteTestCfg.ini and is ignored

**Expected behavior**
We should be able to use all desired parameters in the override section (as long as they exit in the section it is supposed to override). So here since sphKernelRadius is a parameter in the com1DFACfg.ini, we should be able to change it!

**Comment by fso42** [comment]
This should be solved with #779, as this also changes the way ini files are merged
