### ISSUE TITLE
Range time diagram problem

### ISSUE THREAD

**Issue by oscar-dick** [avaframe/AvaFrame#782]
**Describe the bug**
Producing the range time diagram data or plotting the diagram are not working.

**To Reproduce**
While running the simulation (python runCom1DFA), I put createRangeTimeDiagram = True. For a coulomb friction model with mu=0.4, the simulation stops. If I put createRangeTimeDiagram = False it is working well. 

![Screenshot from 2022-11-16 15-15-58](https://user-images.githubusercontent.com/115527718/202204010-a7cc7461-796f-42e7-bfc7-f9b00bbcd5aa.png)

In addMaxValuesToDF, it seems like the rangeValue stops at a certain time step, resulting in a size mismatch at the line 1535 of com1DFA (resultsDF.loc[timeStep] = newLine)  

Sometimes the simulation works (for example for Voellmy friction model with mu=0.6, xsi=4000, no error raised and output folder is complete), but then when trying to plot the range time diagram (python runScripts/runRangeTimeDiagram.py), the plot is not made and the following error message is raised: 

![Screenshot from 2022-11-16 15-28-12](https://user-images.githubusercontent.com/115527718/202207152-21a69b25-4374-464d-a7b6-0c457995f989.png)

In distanceTimeAnalysis/approachVelocity it seems that appVelClean is empty, resulting in an error line 767 when calculating the argmax of it. appVelClean being empty seems to come from the fact that rmaxId is empty itself, even though rangeListSorted looks normal and correctly sorted. 

I also tried on the master branch and the same problems appeared.

**Comment by oscar-dick** [comment]
Sorry I run the avalanche on the AvaSeilbahn slope, I send attached a link to the drive where I put the Inputs files, the logfile, and the distanceTimeAnalysisCfg.ini 
https://bfwgvat-my.sharepoint.com/:f:/g/personal/oskar_dick_bfw_gv_at/Eq93NZSFPJpOl66tSFvyKj0BlszvBHrzS_i2h9j-bENmqg?e=Qu6mne

**Comment by fso42** [comment]
First problem (runCom1DFA) confirmed with seilbahn dem and release + the attached com1DFA ini 
[local_com1DFACfg.txt](https://github.com/avaframe/AvaFrame/files/10031784/local_com1DFACfg.txt)
