### ISSUE TITLE
thalweg time plot

### ISSUE THREAD

**Issue by oscar-dick** [avaframe/AvaFrame#788]
When running python runScripts/runThalwegTimeDiagram.py, the resulting thalweg time diagram looks like this: 

![thalwegTime_FT_4dcf23b224](https://user-images.githubusercontent.com/115527718/204243989-7286eadf-97a0-48e5-b0de-0d0569183a38.png)

The surprising scale is due to the avalanche line that I draw on qgis, which is way longer than this avalanche flow (as the simulations go quite far down for some friction models). We can see it here:

![avaSeilbahn_DomainTransformation](https://user-images.githubusercontent.com/115527718/204244601-3a8c6c2e-ebb2-4f89-aa28-0b607123aa8c.png)

Now if I change the extent of the tt diagram in the local_distanceTimeAnalysis to 
yMax = 300 
yMin = -800

and add them in out3Plots/outDistanceTimeAnalysis/plotRangeTime 
xMin = cfgRangeTime['ANIMATE'].getfloat('xMin')
xMax = cfgRangeTime['ANIMATE'].getfloat('xMax')
yMax = cfgRangeTime['ANIMATE'].getfloat('yMax')
yMin = cfgRangeTime['ANIMATE'].getfloat('yMin')

ax.set_ylim([yMin, yMax])
ax.set_xlim([xMin, xMax])

Then the resulting plot looks like: 

![thalwegTime_FT_98f59868ea](https://user-images.githubusercontent.com/115527718/204246458-108a16d1-18c3-41de-ba80-553d9649b520.png)

With Matthias we thought it would interesting to share

**Comment by fso42** [comment]
So the question is: should this be done automatically? I.e. adjust the range based on available data, and not the profile extends...

**Comment by fso42** [comment]
Closing due to no action
