### ISSUE TITLE
Error running from the Advance installation (only with the latest release 1.4)

### ISSUE THREAD

**Issue by LucaDella8** [avaframe/AvaFrame#819]
Hello,
I switch from 1.3 to 1.4 of the Advance installation and now when I'm running a com1DFA simulation I got some errors and the simulation goes in a loop way; it reads the config files but than only produce the configuration output files and the simulation does not start but within the terminal it continues iteratively to create configuration files.
I try a simulation with more polygons (different shp) within the REL input folder. But in the same way as I was doing with the previews version (1.3), without problems.

![Screenshot 2023-02-15 alle 18 41 52](https://user-images.githubusercontent.com/102517410/219111721-4e3d80ea-a19a-4f47-9508-b5a5a2675643.png)
![Screenshot 2023-02-15 alle 18 41 36](https://user-images.githubusercontent.com/102517410/219111724-75b49344-1f09-406d-8497-7bbd77d27c0a.png)
![Screenshot 2023-02-15 alle 18 41 25](https://user-images.githubusercontent.com/102517410/219111726-42e22a10-ba2f-46c7-bea1-d86a5dc5d92d.png)
![Screenshot 2023-02-15 alle 18 41 10](https://user-images.githubusercontent.com/102517410/219111728-93adab4a-0e40-40bb-9c74-b11ae7cd1e3c.png)

OS: MacOs Ventura

Thanks, ciao Luca

**Comment by fso42** [comment]
Hi Luca, 
Thanks for your report!
This seems to relate to how MacOS handles the multiprocessing forking/spawning. 
I will look into this as soon as I'm back at work (on sick leave atm)...

Do you need anything specific that was implemented in 1.4? If not, as a quick fix, you could downgrade to 1.3 and use that in the meantime (pip install avaframe==1.3)...

regards, 
Felix

**Comment by LucaDella8** [comment]
Ciao Felix!
Yess yess for the moment I'm using the 1.3 installed within a different folder.
Good recovery! ciao Luca

**Comment by fso42** [comment]
Hi Luca, 
I think I might have found a solution.  Before I release a new version, could you verify the following for me? I don't have a macOS system available.

Start up python
```
import platform
print(platform.system())
```
Is the result then 'Darwin'  for you?

**Comment by LucaDella8** [comment]
Ciao Felix,
yess the result is Darwin

**Comment by fso42** [comment]
Hi Luca, 
I just released 1.5, it should be fixed now. Please give it a try, and feel free to reopen this issue if it still does not work...

**Comment by LucaDella8** [comment]
Ciao Felix, sorry for the late try...Anyway, now it is working properly!
