### ISSUE TITLE
Problem running 1.5.2 on MacOS

### ISSUE THREAD

**Issue by fso42** [avaframe/AvaFrame#837]
Ciao Felix, since I was not checking anymore and only using the development version, I did not try anymore. Today I was trying with the new version of avaframe but still have problems to use it directly within qgis.

Here the errors that appear. Do you have new suggestions or the same you told me some month ago?
I try with two different version of qgis (3.30.0 RC and 3.28.4 LTR) but more or less I had the same problems. It follow asking to close/restart qgis every time I launch qgis and I still get errors on loading the plugin and on trying to run an avaframe command. It does not find the avaframe module.

![Screenshot 2023-03-22 alle 08 32 56](https://user-images.githu
![Screenshot 2023-03-22 alle 15 27 15](https://user-images.githubusercontent.com/102517410/226937192-19a6ea63-9413-4239-8cd2-e0cc640f8b52.png)
buserconten
<img width="890" alt="Screenshot 2023-03-22 alle 15 25 41" src="https://user-images.githubusercontent.com/102517410/226937102-571c7ba9-6114-410f-8ef9-b2f3f8843af9.png">
t.com/102517410/226937050-b169e9a6-7f4a-4a26-92ba-ed77fdd3e5da.png)

Best regards, Luca

_Originally posted by @LucaDella8 in https://github.com/avaframe/AvaFrame/issues/733#issuecomment-1479685470_

**Comment by fso42** [comment]
@LucaDella8: I did not have time to test it yet, but I got feedback from another MacOS user that he got it to run using a clean conda environment, and installing QGIS via conda-forge https://anaconda.org/conda-forge/qgis . Maybe this might be worth a try for you? (If you didn't do that already :-) )

**Comment by LucaDella8** [comment]
Ciao Felix, installing QGIS via conda was not working for me but I solve the problem installing qgis via homebrew.
